[workspace]
members = [
    "apps/hk-proton-desktop/src-tauri",
    "crates/hk-proton-core",
    "crates/hk-proton-manager",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"

[workspace.dependencies]
base64 = "0.22"
ipnet = { version = "2", features = ["serde"] }
percent-encoding = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_ng = "0.10"
sha2 = "0.10"
thiserror = "2"
time = { version = "0.3", features = ["formatting", "macros", "serde"] }
url = "2"
uuid = { version = "1", features = ["serde", "v4"] }
zeroize = { version = "1", features = ["derive"] }
